// <auto-generated />
using LoggingSQLTest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoggingSQLTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201216205315_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("LoggingSQLTest.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Witcher: Wild Hunt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Doom"
                        });
                });

            modelBuilder.Entity("LoggingSQLTest.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            Text = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            Text = "Fantasy"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            Text = "Action"
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            Text = "RPG"
                        },
                        new
                        {
                            Id = 5,
                            GameId = 2,
                            Text = "Cyberpunk"
                        },
                        new
                        {
                            Id = 6,
                            GameId = 2,
                            Text = "Action"
                        },
                        new
                        {
                            Id = 7,
                            GameId = 3,
                            Text = "Shooter"
                        },
                        new
                        {
                            Id = 8,
                            GameId = 3,
                            Text = "Action"
                        },
                        new
                        {
                            Id = 9,
                            GameId = 3,
                            Text = "Sci-fi"
                        });
                });

            modelBuilder.Entity("LoggingSQLTest.Models.Tag", b =>
                {
                    b.HasOne("LoggingSQLTest.Models.Game", "Game")
                        .WithMany("Tags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("LoggingSQLTest.Models.Game", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
